import overview from "@/lib/mock/overview.json";
import type { OverviewData } from "@/lib/types";
import { FeedHealthGauge } from "@/components/dashboard/FeedHealthGauge";
import { PlatformChips } from "@/components/dashboard/PlatformChips";
import { TierSection } from "@/components/dashboard/TierSection";
import { RecommendationBanner } from "@/components/dashboard/RecommendationBanner";

const data = overview as OverviewData;

export default function OverviewPage() {
  return (
    <div className="min-h-[100dvh] bg-ground">
      <main className="shell pb-section pt-block">
        <p className="text-fluid-sm text-muted">Sample analysis · YouTube data, last 7 days</p>

        <section className="relative mt-block animate-rise-in overflow-hidden rounded-lg border border-border bg-surface p-block">
          <div
            className="pointer-events-none absolute -left-16 -top-16 h-64 w-64 rounded-full bg-accent opacity-[0.07] blur-3xl"
            aria-hidden="true"
          />
          <div
            className="pointer-events-none absolute -bottom-20 -right-10 h-64 w-64 rounded-full bg-accent-2 opacity-[0.1] blur-3xl"
            aria-hidden="true"
          />
          <div className="relative flex flex-col items-center gap-block text-center sm:flex-row sm:items-center sm:text-left">
            <FeedHealthGauge score={data.feedHealth} />
            <div className="min-w-0 flex-1">
              <h1 className="text-balance font-display text-fluid-2xl font-semibold leading-tight text-ink">
                Your feed leans on <span className="text-accent">stoicism and grind culture</span>{" "}
                this week.
              </h1>
              <p className="mt-2.5 max-w-[52ch] text-fluid-base text-ink-soft">
                Nothing alarming. Just enough of a pattern to be worth a look below.
              </p>
              <div className="mt-5 flex justify-center sm:justify-start">
                <PlatformChips platforms={data.platforms} />
              </div>
            </div>
          </div>
        </section>

        <div className="mt-section space-y-section">
          {data.tiers.map((tier) => (
            <TierSection key={tier.id} tier={tier} />
          ))}
        </div>

        <div className="mt-section">
          <RecommendationBanner text={data.recommendation} />
        </div>

        <footer className="mt-section border-t border-border pt-block">
          <p className="max-w-[68ch] text-fluid-xs leading-relaxed text-muted">
            Atlas is a research prototype, not a diagnostic or monitoring tool. Scores are
            generated by matching feed text against a masculinity-content classification framework
            and are shown alongside their source evidence so you can judge them yourself. Your data
            stays on your device, and analysis only runs when you ask for it.
          </p>
        </footer>
      </main>
    </div>
  );
}
